services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: mailer
      POSTGRES_PASSWORD: mailerpass
      POSTGRES_DB: mailerdb
    ports: ["5432:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mailer -d mailerdb"]
      interval: 5s
      timeout: 3s
      retries: 10

  adminer:
    image: adminer
    ports: ["8081:8080"]
    depends_on: ["db"]

  mail-service:
    image: ${MAIL_IMAGE:-ghcr.io/re-21-12/mailer-service:latest}
    depends_on:
      - backend
    networks:
      - server
      - traefik-public-attachable    
    environment:
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - EMAIL_TIMEOUT=${EMAIL_TIMEOUT}
      - SERVER_PORT=${SERVER_PORT}
      - SERVER_HOST=${SERVER_HOST}
      - DB_DSN=postgres://mailer:mailerpass@db:5432/mailerdb?sslmode=disable

volumes:
  pgdata:

networks:
  server:
    driver: overlay
    attachable: true
    external: true
  traefik-public-attachable:
    external: true